version: '3.6'
services:
    genie:
        build:
            context: Geniejl/
        expose: 
            - "8000"
        env_file: 
            - config.env
        restart: always
    caddy:
        build: 
            context: Caddy/
        ports:
            - "80:80"
            - "443:443"
        depends_on: 
            - "genie"
        restart: always